### ISSUE TITLE
Phone number is aligned to the right

### ISSUE THREAD

**Issue by eyalway2cu** [Way2CU/Ahmad-Two-Site#3]
![image](https://cloud.githubusercontent.com/assets/7808985/25659151/20313902-300f-11e7-851e-657e437d4b51.png)
The + sign should show up to the left of the number as well as the phone icon.

**Comment by MeanEYE** [comment]
This was probably done to force icon to be on the left. Forcing direction is somewhat of a solution but not all that good when you have symbols in there. As I see it we have couple of ways to fix this but best solution would probably be to update generic header template to support both icon positions.
